# Generated by Django 6.0.5 on 2026-06-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id_cardapio', models.AutoField(primary_key=True, serialize=False)),
                ('data_criado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cardapio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('senha', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cpf',
            fields=[
                ('id_cpf', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'db_table': 'cpf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_denuncia', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('data_feita', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'denuncia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'endereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id_estabelecimento', models.AutoField(primary_key=True, serialize=False)),
                ('qr_code', models.TextField(blank=True, null=True, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('imagem', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('aberto', models.BooleanField(default=True)),
                ('media_nota', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'estabelecimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favoritar',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_postagem_cliente', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favoritar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavoritarEstabelecimento',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_estabelecimento', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favoritar_estabelecimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'foto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id_postagem', models.AutoField(primary_key=True, serialize=False)),
                ('legenda', models.TextField(blank=True, null=True)),
                ('avaliacoes', models.IntegerField(blank=True, null=True)),
                ('imagem', models.TextField(blank=True, null=True)),
                ('vibe', models.CharField(blank=True, max_length=20, null=True)),
                ('musica', models.CharField(blank=True, max_length=30, null=True)),
                ('fila', models.CharField(blank=True, max_length=20, null=True)),
                ('preco', models.CharField(blank=True, max_length=10, null=True)),
                ('seguranca', models.CharField(blank=True, max_length=20, null=True)),
                ('pessoas', models.IntegerField(blank=True, null=True)),
                ('tempo_espera', models.CharField(blank=True, max_length=20, null=True)),
                ('metodo_presenca', models.CharField(blank=True, max_length=10, null=True)),
                ('data_postagem', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'postagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id_presenca', models.AutoField(primary_key=True, serialize=False)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('metodo', models.CharField(blank=True, max_length=10, null=True)),
                ('data_confirmada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presenca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_incluido', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id_reacao', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reacao', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'reacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='baladas.usuario')),
                ('favorito', models.BooleanField(blank=True, null=True)),
                ('curtido', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='baladas.usuario')),
            ],
            options={
                'db_table': 'proprietario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostagemCliente',
            fields=[
                ('id_postagem', models.OneToOneField(db_column='id_postagem', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='baladas.postagem')),
                ('nota', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'postagem_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostagemEstabelecimento',
            fields=[
                ('id_postagem', models.OneToOneField(db_column='id_postagem', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='baladas.postagem')),
                ('promocoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'postagem_estabelecimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostagemEvento',
            fields=[
                ('id_postagem', models.OneToOneField(db_column='id_postagem', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='baladas.postagem')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('promocao', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('imagem', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'postagem_evento',
                'managed': False,
            },
        ),
    ]
